### ISSUE TITLE
use a plan file instead of injecting text

### ISSUE THREAD

**Issue by michaelneale** [square/goose-vscode#14]
Instead of injecting content to terminal directly, can write tmp yaml file with content of this format: 

```yaml
kickoff_message: |
    This will follow tasks as given for the project and then try to complete them without input. 
    exit when finished or attempt is finished after trying.

tasks:
 - look at current project context to see how to build and run tests, looking at any build files, workflow files
 - if you can work out how to test it, then attempt the following enhancement, otherwise exit as a failure
 - add a welcome message on start that says "boop mcgoop" to main.dart
 - if successful write  to a file called ./success, and if a failure to ./failure
 -
```

and then start goose with --plan - makes for cleaner startup in IDE
